In [ ]:
from google.colab import files
import pandas as pd
from IPython.display import display

try:
    # 1) Upload the file
    uploaded = files.upload()
    csv_path = list(uploaded.keys())[0]
    print("✅ Uploaded:", csv_path)

    # 2) Load CSV directly into a DataFrame
    df = pd.read_csv(csv_path, low_memory=False)

    # 3) Show top 10 rows
    print("\n📄 Top 10 rows:")
    display(df.head(10))

    # 4) (Optional) show columns and shape
    print("\nColumns:", list(df.columns))
    print("Shape:", df.shape)

except Exception as e:
    print("[info] Upload or loader failed:", e)

Saving q_quora.csv to q_quora.csv
✅ Uploaded: q_quora.csv

📄 Top 10 rows:

,id,qid1,qid2,question1,question2,is_duplicate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Columns: ['id', 'qid1', 'qid2', 'question1', 'question2', 'is_duplicate', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12']
Shape: (404351, 13)

In [ ]:
display(df.head(10))

,id,qid1,qid2,question1,question2,is_duplicate,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
cols_to_drop = [
    'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8',
    'Unnamed: 9', 'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'question1_clean' 'question2_clean'
    ]
df = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

display(df.head(10))

,id,qid1,qid2,question1,question2,is_duplicate
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0

In [ ]:
# 1) Pandas dtype
print("Pandas dtype:", df["is_duplicate"].dtype)

# 2) Python types of first 20 values
print("\nPython types of first 20 values:")
print(df["is_duplicate"].head(20).apply(type))

# 3) Unique values (up to 50)
print("\nUnique values in the column (first 50):")
print(df["is_duplicate"].unique()[:50])

# 4) Unique Python types in the whole column
print("\nUnique Python data types present:")
print({type(x) for x in df["is_duplicate"]})

Pandas dtype: object

Python types of first 20 values:
0     <class 'str'>
1     <class 'str'>
2     <class 'str'>
3     <class 'str'>
4     <class 'str'>
5     <class 'str'>
6     <class 'str'>
7     <class 'str'>
8     <class 'str'>
9     <class 'str'>
10    <class 'str'>
11    <class 'str'>
12    <class 'str'>
13    <class 'str'>
14    <class 'str'>
15    <class 'str'>
16    <class 'str'>
17    <class 'str'>
18    <class 'str'>
19    <class 'str'>
Name: is_duplicate, dtype: object

Unique values in the column (first 50):
['0' '1'
 'Do bullets travel faster than the speed of sound when shot from a gun? If not, is it possible? If they do, what gun and how much devastation occurs?'
 'My sister told my crush that I like her without me asking her to do so. What should I do now?'
 ' how would this change the plot for the whole RR story?'
 'What were the greatest achievements of the Persian Empire?'
 'What are the best places to visit in Japan to get a feel for their latest technological advancements?'
 'My boyfriend wants to have sex with me . And I have mixed feelings regarding that. Should I do it or not ?'
 ' mass communication or pharmacy?'
 'What if we are actually moving back in time? Can one differentiate a backward flow of time from forward flow?'
 "I am in love with my classmate, I am gay and he's straight, what should I do?"
 'Does Donald Trump get to deduct his campaign expenses from his taxes?'
 ' 2) share bonanza' ' is this okay?' 'What are some TL'
 'What do Quora users feel about the concept of heaven and hell irrespective of their religions? Can good and bad people end up in same place up there?'
 ' how can I plan that?' 'p:1%7C'
 "Has anyone ever heard of a friend forgiving his friend's having sex with his wife, and their being friends again?"
 'Why do people of some races seem to be better at certain sports?'
 ' how do recover my password?' ' stocks or a bank account?'
 " Netbeans or Eclipse and whats the difference between these two IDE' s?"
 'Which Indian states are well known in other countries?'
 'Are you fonder of Nietzsche or Kierkegaard?'
 'My ideal girl is out of my reach. Should I settle for what I can get?'
 " Pope Julius II doesn't die in 1513. How's the world different?"
 "I'm a woman. How do I make gay friends?" ' Tupac or Biggie. Why?'
 'Can humans eat cooked chicken bones?' ' or feel thoughts?'
 ' how is it so popular?' ' Am I allowed take the JEE and apply to IIT?'
 ' what does this say about the relation between photons and gravity (tons) and which particles would bend upwards?'
 "Why would a girl on earth be easily attracted by 'Superman', but not a guy who has made his career on his own, saves lives or makes lives of people easy?"
 "Which is India's highest peak?" ' foundation or BB cream?'
 'How is symbolism used in writing?'
 " is it illegal to tamper with my own food (i.e. dropping a pizza in the toilet and then storing it) knowing they'll eat it?"
 'My dad is a professional gambler and he gave my sister and me each $25k. The first one of us who doubles the money anyhow wins another $250k. Should I just bet all at once in Roulette?'
 'I have a great idea for an app which requires extensive coding skills, but I dont have any basic knowledge. What should I do?'
 'I am a woman in love with my gay best friend. He has said there is something deep in our friendship, but he is gay. How do I get over him?'
 ' how should I study chemistry?' ' “Anal sex.”?'
 ' everything else is secondary. Am I wrong?'
 ' to live in a developed nation?'
 'What does it feel like to have a man ejaculate inside your anus (without a condom)?'
 ' how do I undo this?' 'Who has the highest IQ in India?'
 'Is MCA from IGNOU worthfull course?']

Unique Python data types present:
{<class 'str'>}

In [ ]:
# # Convert all values to string for safe checking
# temp = df["is_duplicate"].astype(str).str.strip()

# # Identify rows that do NOT start with "0" or "1"
# invalid_rows = df[~temp.str.match(r"^[01]")]

# print("🔍 Rows that do NOT start with '0' or '1':", invalid_rows.shape)
# display(invalid_rows.head(50))

In [ ]:
import re
import string
from IPython.display import display

# -------------------------------
# 1. Cleaning function
# -------------------------------
def clean_basic(text: str) -> str:
    text = str(text)

    # remove HTML tags
    text = re.sub(r"<.*?>", " ", text)

    # remove [math] ... [/math] tags
    text = re.sub(r"\[/?math\]", " ", text)

    # remove punctuation
    text = text.translate(str.maketrans("", "", string.punctuation))

    # collapse extra whitespace
    text = re.sub(r"\s+", " ", text).strip()

    return text

# -------------------------------
# 2. Apply cleaning to both columns
# -------------------------------
df["question1_clean"] = df["question1"].apply(clean_basic)
df["question2_clean"] = df["question2"].apply(clean_basic)

# -------------------------------
# 3. Preview
# -------------------------------
display(df[["question1", "question2", "question1_clean", "question2_clean"]].head(10))

,question1,question2,question1_clean,question2_clean
0,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...
1,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,What is the story of Kohinoor KohiNoor Diamond,What would happen if the Indian government sto...
2,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...
3,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,Why am I mentally very lonely How can I solve it,Find the remainder when 2324 is divided by 2423
4,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,Which one dissolve in water quikly sugar salt ...,Which fish would survive in salt water
5,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",Astrology I am a Capricorn Sun Cap moon and ca...,Im a triple Capricorn Sun Moon and ascendant i...
6,Should I buy tiago?,What keeps childern active and far from phone ...,Should I buy tiago,What keeps childern active and far from phone ...
7,How can I be a good geologist?,What should I do to be a great geologist?,How can I be a good geologist,What should I do to be a great geologist
8,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",When do you use シ instead of し,When do you use instead of and
9,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,Motorola company Can I hack my Charter Motorol...,How do I hack Motorola DCX3400 for free internet

In [ ]:
# Make sure pandas prints all columns and rows
display(df.head(10))

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean
0,0,1,2,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...,0,What is the step by step guide to invest in sh...,What is the step by step guide to invest in sh...
1,1,3,4,What is the story of Kohinoor (Koh-i-Noor) Dia...,What would happen if the Indian government sto...,0,What is the story of Kohinoor KohiNoor Diamond,What would happen if the Indian government sto...
2,2,5,6,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...,0,How can I increase the speed of my internet co...,How can Internet speed be increased by hacking...
3,3,7,8,Why am I mentally very lonely? How can I solve...,Find the remainder when [math]23^{24}[/math] i...,0,Why am I mentally very lonely How can I solve it,Find the remainder when 2324 is divided by 2423
4,4,9,10,"Which one dissolve in water quikly sugar, salt...",Which fish would survive in salt water?,0,Which one dissolve in water quikly sugar salt ...,Which fish would survive in salt water
5,5,11,12,Astrology: I am a Capricorn Sun Cap moon and c...,"I'm a triple Capricorn (Sun, Moon and ascendan...",1,Astrology I am a Capricorn Sun Cap moon and ca...,Im a triple Capricorn Sun Moon and ascendant i...
6,6,13,14,Should I buy tiago?,What keeps childern active and far from phone ...,0,Should I buy tiago,What keeps childern active and far from phone ...
7,7,15,16,How can I be a good geologist?,What should I do to be a great geologist?,1,How can I be a good geologist,What should I do to be a great geologist
8,8,17,18,When do you use シ instead of し?,"When do you use ""&"" instead of ""and""?",0,When do you use シ instead of し,When do you use instead of and
9,9,19,20,Motorola (company): Can I hack my Charter Moto...,How do I hack Motorola DCX3400 for free internet?,0,Motorola company Can I hack my Charter Motorol...,How do I hack Motorola DCX3400 for free internet

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404351 entries, 0 to 404350
Data columns (total 8 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               404351 non-null  int64
 1   qid1             404351 non-null  int64
 2   qid2             404351 non-null  int64
 3   question1        404350 non-null  object
 4   question2        404349 non-null  object
 5   is_duplicate     404351 non-null  object
 6   question1_clean  404351 non-null  object
 7   question2_clean  404351 non-null  object
dtypes: int64(3), object(5)
memory usage: 24.7+ MB

In [ ]:
# Extract rows where is_duplicate is NOT 0 or 1  → junk dataset

junk = df[~df["is_duplicate"].isin(["0", "1"])]

# Extract rows where is_duplicate is 0 or 1 → clean dataset
clean = df[df["is_duplicate"].isin(["0", "1"])]

# Reset index for both datasets (optional but neat)
junk = junk.reset_index(drop=True)
clean = clean.reset_index(drop=True)

print("🔍 Junk dataset shape:", junk.shape)
print("✅ Clean dataset shape:", clean.shape)

print("\nUnique values in CLEAN dataset:")
print(clean["is_duplicate"].unique())

print("\nUnique values in JUNK dataset:")
print(junk["is_duplicate"].unique())

🔍 Junk dataset shape: (336, 8)
✅ Clean dataset shape: (404015, 8)

Unique values in CLEAN dataset:
['0' '1']

Unique values in JUNK dataset:
['Do bullets travel faster than the speed of sound when shot from a gun? If not, is it possible? If they do, what gun and how much devastation occurs?'
 'My sister told my crush that I like her without me asking her to do so. What should I do now?'
 ' how would this change the plot for the whole RR story?'
 'What were the greatest achievements of the Persian Empire?'
 'What are the best places to visit in Japan to get a feel for their latest technological advancements?'
 'My boyfriend wants to have sex with me . And I have mixed feelings regarding that. Should I do it or not ?'
 ' mass communication or pharmacy?'
 'What if we are actually moving back in time? Can one differentiate a backward flow of time from forward flow?'
 "I am in love with my classmate, I am gay and he's straight, what should I do?"
 'Does Donald Trump get to deduct his campaign expenses from his taxes?'
 ' 2) share bonanza' ' is this okay?' 'What are some TL'
 'What do Quora users feel about the concept of heaven and hell irrespective of their religions? Can good and bad people end up in same place up there?'
 ' how can I plan that?' 'p:1%7C'
 "Has anyone ever heard of a friend forgiving his friend's having sex with his wife, and their being friends again?"
 'Why do people of some races seem to be better at certain sports?'
 ' how do recover my password?' ' stocks or a bank account?'
 " Netbeans or Eclipse and whats the difference between these two IDE' s?"
 'Which Indian states are well known in other countries?'
 'Are you fonder of Nietzsche or Kierkegaard?'
 'My ideal girl is out of my reach. Should I settle for what I can get?'
 " Pope Julius II doesn't die in 1513. How's the world different?"
 "I'm a woman. How do I make gay friends?" ' Tupac or Biggie. Why?'
 'Can humans eat cooked chicken bones?' ' or feel thoughts?'
 ' how is it so popular?' ' Am I allowed take the JEE and apply to IIT?'
 ' what does this say about the relation between photons and gravity (tons) and which particles would bend upwards?'
 "Why would a girl on earth be easily attracted by 'Superman', but not a guy who has made his career on his own, saves lives or makes lives of people easy?"
 "Which is India's highest peak?" ' foundation or BB cream?'
 'How is symbolism used in writing?'
 " is it illegal to tamper with my own food (i.e. dropping a pizza in the toilet and then storing it) knowing they'll eat it?"
 'My dad is a professional gambler and he gave my sister and me each $25k. The first one of us who doubles the money anyhow wins another $250k. Should I just bet all at once in Roulette?'
 'I have a great idea for an app which requires extensive coding skills, but I dont have any basic knowledge. What should I do?'
 'I am a woman in love with my gay best friend. He has said there is something deep in our friendship, but he is gay. How do I get over him?'
 ' how should I study chemistry?' ' “Anal sex.”?'
 ' everything else is secondary. Am I wrong?'
 ' to live in a developed nation?'
 'What does it feel like to have a man ejaculate inside your anus (without a condom)?'
 ' how do I undo this?' 'Who has the highest IQ in India?'
 'Is MCA from IGNOU worthfull course?'
 'If Wikipedia crashed and all of it got deleted what would happen to the world?'
 'What are the different positions available in a venture capital firm?'
 'What does this mean?'
 'I would like to incorporate my tech company in Delaware, but operate it out of Canada. My concern is would the company not be considered a residency corporation of Canada, and therefore all Canadian tax law would be applicable?'
 'What is the full form of jio?'
 'How do I get to talk to a customer care executive of HDFC bank?'
 ' in india?'
 'Is the universe infinite? If so, what is it expanding into?'
 "Which function returns if we've reached the end of a file (in C)?"
 'What is the difference between while do and do while C#?'
 ' what could have been the primary cause of instability and what could be done to correct it?'
 ' Kostas Manolas or Alessio Romagnoli?' ' GHZ or RAM?'
 'What are some of the highest paying jobs in India?'
 'I am self-employed and my parents are the directors of my venture. Can I use their Recommendation Letters while applying for PhD at US universities?'
 ' what strategy do you recommend for reinvesting this money given current markets and the upcoming election?'
 'Is it bad that I do not want to make a man leave his family because they have children, and I would rather them grow up with a father, as my dad left when I was young to be with another woman and we never had a relationship since then?'
 'Does coming from a poor country decrease the likelihood of f1 visa approval?'
 'What are some sensible trolls and memes?' ' what are those dimensions?'
 'I got an offer from logistics startup (2014) of 7lpa, as if now am working with HP CTC 5.5 what would be beneficial for me in long run, plz suggest?'
 ' in case I encounter difficulties?'
 "I told my best friend I love her, but she's pretending like nothing happened, still as good friends as we were before. How do I attract her?"
 'How does it feel to not sleep for 24-36 hours?'
 'How to not too salty fish sauce during salted?'
 'I have left Larsen and tubro ltd within 5 month and after 4 month gap, joined another, again after 6 month I left this jobless .what should I do?'
 'Is there anything infinite in our universe?'
 ' it is a two member LLC. I filed Schedule K1 for last year with my personal tax return and my partner did the same thing as me. Do we still have to file a Form 1065 separately?'
 '\\' " will it show up for a UA for my parole in six days' time?" ' why?'
 'How many IITians are there on Quora?'
 "What does the UK's Labour Party believe should be done to improve mental health care?"
 ' how do they get energy for their movement?'
 'How many fund provide for m l a?' " which one's better?"
 'I am 22 and I am only 157 cm.How can I increase my height up to 168 cm?'
 "Which is the world's oldest civilization?" 'a+c=13'
 ' doEs this mean she block me?' ' the system or the society?'
 'Was time created first or universe?'
 " I was added to all her groups and her account's blocked settings migrated into mine. How do I solve this? How do I ensure she's not receiving messages meant for me?"
 'How do I change who I am?'
 'Why would an intelligent person vote for Donald Trump?'
 ' tailgating a slow driver or passing a the slow driver in a no passing zone?'
 ' surely it must be expanding into something?'
 'What is the day schedule of a full time home tutor?'
 'As an American, how would i procure a Land Rover Discovery diesel?'
 "What were Sir Francis Bacon's most important contributions to the scientific revolution?"
 ' review of the literature'
 ' the Nvidia GTX 1080 or the Nvidia Quadro M4000?' ' what should I do?'
 'Is it better to go for a job just after your graduation?'
 ' I would appreciate if the answer explains physical significance?'
 "How do you deal with always being in someone's shadow?"
 "How does one speak to a Vodafone customer care executive quickly? I'm sick and tired of waiting and listening to the same monotonous IVRS!!"
 " is it wrong to live most of our life in dream if it's not possible to experience the same in reality?"
 ' premise: God is true' 'How can I stop loving my friend?'
 ' one dimension is for time and the others space. What are the other dimensions?'
 'Do employees at Tribune Publishing Company have a good work-life balance? Does this differ across positions and departments?'
 'What would be an ideal sample size to get a more accurate exit poll estimate for a country like India and how does it compare with the largest exit polls conducted typically?'
 " he's straight. What should I do?" ' her/his career goals? How'
 "My employer didn't pay me, but had filed income tax as if I was paid. What should I do now?"
 "I don't have jio sim no. on its pack. what should I do?"
 'I am thinking of starting a business to provide stalking services via social media for clients looking to keep tabs on friends and family. Is this a feasible idea, and is there a market for it?'
 'If society approves gay marriage, should it approve siblings to get married? How are these two relationships different from a moral viewpoint?'
 'How can i find a partial sum formula for: [math]1\\cdot 1!+2\\cdot 2!+3\\cdot 3!\\ldots n\\cdot n![/math]?'
 'What are the options for someone who is very good in swimming, like an Olympic player, if they get caught in a sea wreck? Will their swimming skills help them to survive?'
 'What is the relationship between variance and standard deviation?'
 'What will be your starcast if Mahabharat is made in tollywood?'
 "I have heard that most Indians don't use toilet paper, is this true?"
 ' I used to work for them as a cashier. What should be my next steps to find another job?'
 'Why do I love Cersei Lannister?'
 "I wouldn't say I'm depressed, but I have a lot of anxiety and struggle to find motivation for things. What should I do?"
 ' will it hurt or feel good?'
 'How is the instinct to allow someone to hurt you after hurting them natural?'
 " lease ending so I stopped paying the rent. What will happen if he doesn't my location as I moving to another state?"
 ' what would you tell your 14-year-old self?' ' M.Arch or M.Plan?'
 ' what is the best topic that i may present for students?'
 'Who is the artist who created this image?'
 ' can I work from UK remotely for 2-4 weeks per year?'
 ' Go Pro Karma or DJI Mavic?'
 'Is it OK if a teacher says, "I don\'t know" to students?' '3 mean?'
 'What is the importance of molar mass?'
 'How do presidential elections work in the US, how do the compare to the presidential elections in Nicaragua?'
 " it doesn't happen if I crash)?"
 ' how much of a share should I give him?'
 "How do I treat my 8-year-old younger brother if I don't get time to guide him?"
 'How do I develop a game or an app using any programming editor? (Turbo C, Visual Studio, Eclipse, etc.)'
 'What is the best way to get rid of a 2-3 week pregnancy?'
 ' please advice how to go about it?' ' ha'
 'What is the difference between ";" and ","?'
 ' now she is totally avoiding me. What do I do?'
 ' there is a way to eliminate tuition debt within a year. Ask for more information.'
 " by achieving success under any circumstances or by finding satisfaction in what we have!' Which way is correct?"
 ' ?' ' which is the best time to do so?'
 ' can anyone suggest a better workflow for task management based on human psychology?'
 'Where did Vulncat by HP Fortify disappear?'
 'Is there any app to adjust my rough voice to better?'
 'What is it like to study and live in Indonesia as a foreign student?'
 'What is better to earn good money for a fresher, a job or a business?'
 'Is Mark Zuckerberg the best programmer in the world?'
 ' are they also against spay and neuter?'
 'What are some of the best presidential campaigns in U.S. history?'
 'What would happen if I left college for a semester? Would I still be able to go back and pick up where I left off?'
 ' Finkibi & Spinko. : How long does it take to play a game of finkeybe?'
 ' to be street smart or book smart?'
 'What would happen if India stopped the water flowing into Pakistan? How devastating would it be for Pakistan and how would the international community react to it?'
 ' are there any problems that have arisen? Where can I find ratings?'
 'I have a great app idea. What should I do with it? What are my choices?'
 ' 33x33=?'
 ' is it true that dogs know beforehand that their owners are coming home?'
 " isn't its too late for me to learn English grammar?"
 'I just found out after 5 years of marriage that my wife never really loved me. We had a daughter together as well, but still she feels nothing towards me. How do I handle this?'
 ' “This question needs improving.” What do you do?'
 'What are the politics of The Daily Beast? How are they applied?'
 'If I smoked meth for a month how long for a UA to show clean?'
 'What do you think about the Galaxy Note 4?'
 "I'm a latina 23 years old woman (Pear body) ... I've been gaining weight the last months and I want to start losing it, to feel confident and also for my health (I have diabetic people in my family), is there any diet and exercises that I could try?"
 ' mean in Java?' 'What does this mean in C?'
 'Was  Jesus Christ born on earth?'
 'How do I build back links for my WordPress site?' ' Bank or Stocks?'
 ' press a button & then leave & recollect them later with clothes completely dry? Is it available in India?'
 ' what is the value per view?'
 'Is it irrational to walk on a college campus when going to classes?'
 ' concerning his aspirations as a presidential candidate?'
 ' would that be a defeat or a victory for democracy?'
 'What kind of an organic solvent' ' should I stay or go home?'
 " do you have any scientific and tangible evidence that God doesn't exist?"
 'Why are so many IITians on Quora?'
 'What is exactly BIT FIELDS when it is used?'
 'Is violence innate in the human race? What purpose did or does it serve? Why does it persist?'
 'If you have to choose another biomolecule to make an enzyme other than proteins what would be your choice and why?'
 'What are some interesting cases of income tax which changed the tax laws in India?'
 "What's the difference between washboard abs and six pack abs?"
 'Anti-Muslim activist Katharine Gorka named to Homeland Security Transition Team'
 ' how many pots and pans do you usually have to wash up afterwards and how many remain unwashed after the coffee is served?'
 "My boyfriend wants to try anal but I don't know how it feels, what should I do?"
 'Is Herschel crater on the moon Mimas needed to be created at special period of the formation, in order for it to be "frozen" at this particular shape?'
 'What is the difference between variance and standard deviation?'
 'I<cards' ' AWA-3.5)?'
 ' did he make a big enough impact during his time on Earth?'
 'Why was William S. Burroughs such an influential writer?'
 "I'm a 13 year old lesbian and am in love with my best, straight friend. What do I do?"
 "How does Trump plan on not touching Social Security when he doesn't want tax increases to pay for that?"
 'What is the difference between standard deviation and variance? Gives an explaination with example?'
 'How do presidential elections work in the US, how do the compare to the presidential elections in Uruguay?'
 'What is it like to be a submariner?'
 'When a group of people are facing mass execution why do they not usually rise up to save themselves?'
 ' how do I do that?'
 " at least 2 bottles of spirits a week and 5 pints a night. I'm quiting for 30 days. What will that do for me?"
 'I am 17. I am a very motivated type of person with many leadership skills and I want to become an entrepreneur in business management. How can I make money work for me in my favor? For example how do I turn my assets into money makers over spending my money on liabilities?'
 ' running or walking? What are some cardio exercises for weight gain?'
 ' what would happen if someone jumped into it?'
 'How will the presidential election affect FOREX?'
 'I called airtel customer care, got a reply from BJP, Why?' '-2 0 2'
 ' did Mandela sell out Black people?'
 ' a low pitch sound or a high pitch sound? Why?'
 ' 24 hours later my finger is still tingly/numb?'
 'How do I get a job in Microsoft or Google after complete a B.Tech in computer science?'
 'What is the difference between ":=" and "::=" ?'
 'Does the apocalypse have a soundtrack?'
 " that you just have to lose fat overall. So how do you lose chin fat if you're fit?"
 'If I download movies or games using utorrent in Delhi, India, is it illegal or is there any fine I have to pay if they track me down? Is this true?'
 'Who will win: lizard or frog?'
 'Had Kashmir been part of Pakistan would India behave the same way as Pakistan does?'
 ' is there any fix?'
 ' yet why does Donald  Trump stir segments of white people in the GOP base ?'
 ' I’m extremely uncomfortable with it. What should I do?'
 ' what does it mean?'
 'What is the most frustrating thing about your job or business? In other words, what keeps you up at night?'
 ' The Clone Wars?'
 ' While she is away at college how can I transfer money from my account to hers?'
 'DR version of World War I?'
 ' what is the best answer we should give to confirm our selection?'
 "What was Steve Jobs' cause of death?"
 'What is current account and savings account?' ' what do I do?'
 ' what is your advice for me?'
 'What were those specific steps of the government in the 1950-60 that amounted to the imposition of Hindi?'
 ' and seem like Muslims worship the Kaaba?'
 "I am 19. I think I might be one week pregnant. I am really scared. I don't want my parents to get to know. I live in Bangalore. What do I do?"
 'Who is the most beautiful woman on Game of Thrones?'
 ' when he looks like this below?' "' mean?"
 "I am 7 weeks pregnant. I have been wanting to have a baby for a while now. But now that I am having a baby I constantly keep feeling like I'm stuck and I don't want it. What is wrong with me?"
 'Since the beginning, I have supported Sanders and was saddened when he dropped out. Why should I vote for you, rather than vote for Jill stein?'
 ' how do I keep track of what my children do from my desk?'
 ' can we stop them?' ' are they really kissing?'
 ' Deadline being this september to give both exams to apply for fall 2017?'
 'What is a scope resolution operator in PHP? How is it used?'
 'What advice would you give to your 18-year-old self?'
 ' Information science (IE) at Ambedkar Institute of technology or CSE at Global Academy of Technology?'
 'How do I get a six pack?'
 "Atheists, can you please post the evidence you have discovered that makes you believe that God doesn't exist?"
 'What is your college life story in brief?'
 'How does work address affect you when filing state taxes?'
 'What is an antenna?' ' 3 sauces' ' Arjit Singh or Atif Aslam?'
 ' i.e. increase the quality of the video without downloading the video?'
 "Why won't my boyfriend have sex with me?"
 'Can I get MBBS seat in private medical colleges with 316 marks in NEET 2016?'
 ' then is patience a virtue?' ' Marshmallow?'
 ' the second has sequence number 170.'
 'Can you suggest an order in which I should go about learning chords?'
 'Is Pokemon Go the first of its kind and why is it so popular?'
 ' Audio Technica m20x or Sennheiser 203?'
 'If an audio file is converted from MP3 to WAV back to the same bitrate MP3, will there be any loss in quality relative to the original file?'
 "I had sex with my gf without using condom on the 25th sept Morning, she had ipill at 26th sept night, She hasn't got her period yet & its 6th October  (usually she gets period in the 1st week of the month). I'm worried, has she got pregnant?"
 "I'm gay I feel in love with a straight boy. He is also my friend. What should I do?"
 'Here is my new discovery in math which is true but impossible to prove. 2 never equal = C^n where C<2 ?'
 'What makes Pokémon GO so popular?'
 " she says she's not feeling us anymore and wants to break up. Is it time to move on?"
 '}[/math] and [math]\\texttt{if(1) {}}[/math]?'
 ' should I buy the MacBook Pro MGXC2HN/A or wait for the 2015 model to be released?'
 "How would we solve the differential equation y'sinx=ylogy?"
 ' they eventually stop working. Why is this?' ' in C++?'
 "How long/ loud would I have to scream at a mug of water to make it boil, assuming the mug won't crack?"
 " it only has one tick and I can't see the last seen time - Have I been blocked?"
 "A Song of Ice and Fire: Is R'hllor a real god?"
 'How can judge take fresh cognizance in Indian courts based on new supplementary chargesheet?'
 "Why didn't Gimli know none of his kin were alive at Moria?"

In [ ]:
print("===== CLEAN → is_duplicate (first 50 values) =====")
print(clean["is_duplicate"].head(50).tolist())

print("\n===== JUNK → is_duplicate (first 50 values) =====")
print(junk["is_duplicate"].head(50).tolist())

===== CLEAN → is_duplicate (first 50 values) =====
['0', '0', '0', '0', '0', '1', '0', '1', '0', '0', '0', '1', '1', '1', '0', '1', '1', '0', '1', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '1', '0', '1', '1', '0', '0', '0', '0', '0', '1', '0', '0', '0', '0', '0', '0', '0', '0', '0', '1', '1']

===== JUNK → is_duplicate (first 50 values) =====
['Do bullets travel faster than the speed of sound when shot from a gun? If not, is it possible? If they do, what gun and how much devastation occurs?', 'My sister told my crush that I like her without me asking her to do so. What should I do now?', ' how would this change the plot for the whole RR story?', 'What were the greatest achievements of the Persian Empire?', 'What are the best places to visit in Japan to get a feel for their latest technological advancements?', 'My boyfriend wants to have sex with me . And I have mixed feelings regarding that. Should I do it or not ?', ' mass communication or pharmacy?', 'What if we are actually moving back in time? Can one differentiate a backward flow of time from forward flow?', "I am in love with my classmate, I am gay and he's straight, what should I do?", 'Does Donald Trump get to deduct his campaign expenses from his taxes?', ' 2) share bonanza', ' is this okay?', 'What are some TL', 'What do Quora users feel about the concept of heaven and hell irrespective of their religions? Can good and bad people end up in same place up there?', ' how can I plan that?', 'p:1%7C', "Has anyone ever heard of a friend forgiving his friend's having sex with his wife, and their being friends again?", 'Why do people of some races seem to be better at certain sports?', ' how do recover my password?', ' stocks or a bank account?', " Netbeans or Eclipse and whats the difference between these two IDE' s?", 'Which Indian states are well known in other countries?', 'Are you fonder of Nietzsche or Kierkegaard?', 'My ideal girl is out of my reach. Should I settle for what I can get?', " Pope Julius II doesn't die in 1513. How's the world different?", "I'm a woman. How do I make gay friends?", ' Tupac or Biggie. Why?', 'Can humans eat cooked chicken bones?', ' or feel thoughts?', ' how is it so popular?', ' Am I allowed take the JEE and apply to IIT?', ' what does this say about the relation between photons and gravity (tons) and which particles would bend upwards?', "Why would a girl on earth be easily attracted by 'Superman', but not a guy who has made his career on his own, saves lives or makes lives of people easy?", "Which is India's highest peak?", ' foundation or BB cream?', 'How is symbolism used in writing?', " is it illegal to tamper with my own food (i.e. dropping a pizza in the toilet and then storing it) knowing they'll eat it?", 'My dad is a professional gambler and he gave my sister and me each $25k. The first one of us who doubles the money anyhow wins another $250k. Should I just bet all at once in Roulette?', 'I have a great idea for an app which requires extensive coding skills, but I dont have any basic knowledge. What should I do?', 'I am a woman in love with my gay best friend. He has said there is something deep in our friendship, but he is gay. How do I get over him?', ' how should I study chemistry?', ' “Anal sex.”?', ' everything else is secondary. Am I wrong?', ' to live in a developed nation?', 'What does it feel like to have a man ejaculate inside your anus (without a condom)?', ' how do I undo this?', 'Who has the highest IQ in India?', 'Is MCA from IGNOU worthfull course?', 'If Wikipedia crashed and all of it got deleted what would happen to the world?', 'What are the different positions available in a venture capital firm?']

In [ ]:
print("📊 Percentage distribution in CLEAN dataset:")

# Count occurrences of each value
clean_counts = clean["is_duplicate"].value_counts()

# Convert to percentage
clean_percent = (clean_counts / len(clean)) * 100

# Display both
print(clean_counts)
print("\nPercentage (%):")
print(clean_percent)

📊 Percentage distribution in CLEAN dataset:
is_duplicate
0    254748
1    149267
Name: count, dtype: int64

Percentage (%):
is_duplicate
0    63.054095
1    36.945905
Name: count, dtype: float64

In [ ]:
from sklearn.model_selection import train_test_split

# Split clean dataset into train (80%) and test (20%)
train_clean, test_clean = train_test_split(
    clean,
    test_size=0.20,
    random_state=42,
    shuffle=True
)

print("✅ Training Clean Shape:", train_clean.shape)
print("✅ Testing Clean Shape:", test_clean.shape)

# Optional: show top rows
display(train_clean.head())
display(test_clean.head())

✅ Training Clean Shape: (323212, 8)
✅ Testing Clean Shape: (80803, 8)

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean
114388,114475,226948,226949,Is it possible for an aircraft to have no stal...,How hard is it to be accepted into Cambridge a...,0,Is it possible for an aircraft to have no stal...,How hard is it to be accepted into Cambridge a...
75628,75690,150401,150402,How do I unsubscribe from all email?,How do I unsubscribe from emails?,1,How do I unsubscribe from all email,How do I unsubscribe from emails
394561,394886,574306,771693,What is the best way to whiten your teeth?,How can I whiten my teeth?,1,What is the best way to whiten your teeth,How can I whiten my teeth
306279,306532,601833,601834,Why does the New York Times always posts racis...,How should we mitigate anger against this raci...,0,Why does the New York Times always posts racis...,How should we mitigate anger against this raci...
190788,190935,376951,376952,Why haven't Canada and America merged?,Would America and Canada ever merge?,0,Why havent Canada and America merged,Would America and Canada ever merge

,id,qid1,qid2,question1,question2,is_duplicate,question1_clean,question2_clean
141575,141680,280431,280432,Who are the NFL players with the most Super Bo...,How badly do most NFL players want to win a Su...,0,Who are the NFL players with the most Super Bo...,How badly do most NFL players want to win a Su...
119595,119685,237197,237198,Where can you find the summary of the deals th...,"How do banks like Goldman Sachs, JP Morgan, Mo...",0,Where can you find the summary of the deals th...,How do banks like Goldman Sachs JP Morgan Morg...
275409,275628,541955,541956,How would the Mahabharata changed if Karna and...,Who won the war between Karna and Arjuna?,0,How would the Mahabharata changed if Karna and...,Who won the war between Karna and Arjuna
320836,321097,629934,629935,Can I get a DSLR camera for rent in Chennai?,Where can I rent a DSLR camera in ranchi?,0,Can I get a DSLR camera for rent in Chennai,Where can I rent a DSLR camera in ranchi
256455,256662,65964,505184,"How do I tell if I am a visual, auditory, or k...",I learn by speaking to people or speaking to m...,0,How do I tell if I am a visual auditory or kin...,I learn by speaking to people or speaking to m...

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report
import numpy as np
import pandas as pd

# -----------------------------
# 1. Build TF-IDF on training data (Q1 + Q2 together)
# -----------------------------
# We do NOT modify train_clean / test_clean; we only read from them.

# Combine all questions from training set to build the vocabulary
train_questions_all = pd.concat(
    [train_clean["question1_clean"], train_clean["question2_clean"]],
    axis=0
)

tfidf = TfidfVectorizer(
    lowercase=True,
    ngram_range=(1, 2),     # unigrams + bigrams (you can change this)
    min_df=2,               # ignore very rare terms (optional)
    max_features=100000     # cap features (optional)
)

tfidf.fit(train_questions_all)

# -----------------------------
# 2. Transform Q1 and Q2 separately with SAME TF-IDF
# -----------------------------
# Train
q1_train_tfidf = tfidf.transform(train_clean["question1_clean"])
q2_train_tfidf = tfidf.transform(train_clean["question2_clean"])

# Test
q1_test_tfidf = tfidf.transform(test_clean["question1_clean"])
q2_test_tfidf = tfidf.transform(test_clean["question2_clean"])

# -----------------------------
# 3. Row-wise cosine similarity between Q1 and Q2
#    (TF-IDF vectors are L2-normalized by default → dot product = cosine)
# -----------------------------
# Element-wise multiply and sum across features to get similarity per row
train_sim = q1_train_tfidf.multiply(q2_train_tfidf).sum(axis=1)
test_sim  = q1_test_tfidf.multiply(q2_test_tfidf).sum(axis=1)

# Convert from matrix to 1D numpy array
X_train = np.asarray(train_sim).ravel().reshape(-1, 1)   # shape: (n_samples, 1)
X_test  = np.asarray(test_sim).ravel().reshape(-1, 1)

# -----------------------------
# 4. Prepare labels (WITHOUT changing the original DataFrame)
# -----------------------------
y_train = train_clean["is_duplicate"].astype(int).values
y_test  = test_clean["is_duplicate"].astype(int).values

# -----------------------------
# 5. Train a simple classifier on cosine similarity
# -----------------------------
clf = LogisticRegression()
clf.fit(X_train, y_train)

# -----------------------------
# 6. Evaluate on test set
# -----------------------------
y_pred = clf.predict(X_test)

print("🔢 Test Accuracy:", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report:\n")
print(classification_report(y_test, y_pred))

🔢 Test Accuracy: 0.6186403970149623

📊 Classification Report:

              precision    recall  f1-score   support

           0       0.65      0.84      0.74     50813
           1       0.47      0.24      0.31     29990

    accuracy                           0.62     80803
   macro avg       0.56      0.54      0.53     80803
weighted avg       0.59      0.62      0.58     80803

In [ ]:
import pandas as pd

# Create a DataFrame to hold the test data, true labels, and predictions
results_df = test_clean.copy()
results_df["true_label"] = y_test
results_df["predicted_label"] = y_pred

# Identify false positives (true_label = 0, predicted_label = 1)
false_positives = results_df[
    (results_df["true_label"] == 0) & (results_df["predicted_label"] == 1)
]

# Identify false negatives (true_label = 1, predicted_label = 0)
false_negatives = results_df[
    (results_df["true_label"] == 1) & (results_df["predicted_label"] == 0)
]

print("--- TF-IDF Model Failure Cases ---")
print(f"Total False Positives: {len(false_positives)}")
print(f"Total False Negatives: {len(false_negatives)}")

print("\n--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---")
if not false_positives.empty:
    display(
        false_positives[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false positives found.")

print("\n--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---")
if not false_negatives.empty:
    display(
        false_negatives[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false negatives found.")

--- TF-IDF Model Failure Cases ---
Total False Positives: 7886
Total False Negatives: 22929

--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
4088,I got AIR 617 in a NEST 2015 The cutoff is 90 ...,I got AIR 617 in a NEST 2016 The cutoff is 90 ...,0,1
255222,Who are interested in startup in Pune,Is anyone interested in a startup in Pune,0,1
49214,What apps or services use the Square Connect API,What apps or services use the Square Commerce API,0,1
29144,Should one get married for money,Should one get married,0,1
318811,What are some traditional gifts for a 19th wed...,What are traditional gifts for a 13th wedding ...,0,1

--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
323205,What is the difference between a hobby and a h...,What is the difference between interest and ho...,1,0
334682,Which is the best movie download site,Which are best sites to download movies,1,0
75905,What are effects of 1 or 2 year backlogs in gr...,What are effects of having 1 or 2 year lags in...,1,0
117491,What suggestions can be considered for improvi...,What can we do to improve the Indian education...,1,0
401210,What does it take to be a top writer on Quora,What should I do to become a Top Writer on Quo...,1,0

In [ ]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.0.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 94.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [ ]:
# If gensim is not installed, uncomment this:
# !pip install gensim

from gensim.models import Word2Vec
import numpy as np
import pandas as pd
from sklearn.metrics import f1_score, accuracy_score, classification_report

# ---------------------------------------------------
# 1. Prepare data for Word2Vec training (from TRAIN only)
# ---------------------------------------------------

# Use question1_clean and question2_clean text from train_clean
train_q1_texts = train_clean["question1_clean"].astype(str).tolist()
train_q2_texts = train_clean["question2_clean"].astype(str).tolist()

# Tokenize by simple whitespace split (assuming text already cleaned)
sentences = [q.split() for q in train_q1_texts] + [q.split() for q in train_q2_texts]

# ---------------------------------------------------
# 2. Train Word2Vec model
# ---------------------------------------------------
w2v_model = Word2Vec(
    sentences=sentences,
    vector_size=300,   # embedding size
    window=5,
    min_count=2,
    workers=4,
    sg=1               # 1 = skip-gram, 0 = CBOW
)

word_vectors = w2v_model.wv
embed_dim = word_vectors.vector_size

# ---------------------------------------------------
# 3. Helper: get sentence vector (average of word vectors)
# ---------------------------------------------------
def sentence_to_vec(sentence, word_vectors, embed_dim):
    tokens = sentence.split()
    vecs = []
    for tok in tokens:
        if tok in word_vectors:
            vecs.append(word_vectors[tok])
    if not vecs:  # no known tokens
        return np.zeros(embed_dim, dtype=np.float32)
    vecs = np.array(vecs)
    return vecs.mean(axis=0)

def batch_sentence_vectors(series, word_vectors, embed_dim):
    return np.vstack([
        sentence_to_vec(text, word_vectors, embed_dim)
        for text in series.astype(str)
    ])

# ---------------------------------------------------
# 4. Build sentence vectors for Q1 and Q2 (train + test)
# ---------------------------------------------------

# Train vectors
q1_train_vec = batch_sentence_vectors(train_clean["question1_clean"], word_vectors, embed_dim)
q2_train_vec = batch_sentence_vectors(train_clean["question2_clean"], word_vectors, embed_dim)

# Test vectors
q1_test_vec = batch_sentence_vectors(test_clean["question1_clean"], word_vectors, embed_dim)
q2_test_vec = batch_sentence_vectors(test_clean["question2_clean"], word_vectors, embed_dim)

# ---------------------------------------------------
# 5. Cosine similarity between Q1 and Q2 vectors
# ---------------------------------------------------
def cosine_sim_batch(a, b, eps=1e-8):
    # a, b: shape (n_samples, embed_dim)
    dot_product = np.sum(a * b, axis=1)
    norm_a = np.linalg.norm(a, axis=1)
    norm_b = np.linalg.norm(b, axis=1)
    return dot_product / (norm_a * norm_b + eps)

train_sim = cosine_sim_batch(q1_train_vec, q2_train_vec)
test_sim  = cosine_sim_batch(q1_test_vec, q2_test_vec)

# ---------------------------------------------------
# 6. Prepare labels (without modifying DataFrames)
# ---------------------------------------------------
y_train = train_clean["is_duplicate"].astype(int).values
y_test  = test_clean["is_duplicate"].astype(int).values

# ---------------------------------------------------
# 7. Find best similarity threshold on TRAIN set
# ---------------------------------------------------
thresholds = np.linspace(-1.0, 1.0, 201)  # cosine can be [-1, 1]
best_threshold = None
best_f1 = -1.0

for thr in thresholds:
    y_pred_train = (train_sim >= thr).astype(int)
    f1 = f1_score(y_train, y_pred_train)
    if f1 > best_f1:
        best_f1 = f1
        best_threshold = thr

print(f"🔍 Best threshold on TRAIN: {best_threshold:.4f} with F1 = {best_f1:.4f}")

# ---------------------------------------------------
# 8. Evaluate on TEST set using best threshold
# ---------------------------------------------------
y_pred_test = (test_sim >= best_threshold).astype(int)

test_acc = accuracy_score(y_test, y_pred_test)
print(f"\n✅ Test Accuracy (Word2Vec + cosine threshold): {test_acc:.4f}\n")

print("📊 Classification Report (Test):\n")
print(classification_report(y_test, y_pred_test))

🔍 Best threshold on TRAIN: 0.8500 with F1 = 0.6172

✅ Test Accuracy (Word2Vec + cosine threshold): 0.6074

📊 Classification Report (Test):

              precision    recall  f1-score   support

           0       0.84      0.46      0.60     50813
           1       0.48      0.85      0.62     29990

    accuracy                           0.61     80803
   macro avg       0.66      0.66      0.61     80803
weighted avg       0.71      0.61      0.60     80803

In [ ]:
import pandas as pd

# Create a DataFrame to hold the test data, true labels, and predictions
# Using y_pred_test from the Word2Vec model
results_df_w2v = test_clean.copy()
results_df_w2v["true_label"] = y_test
results_df_w2v["predicted_label"] = y_pred_test

# Identify false positives (true_label = 0, predicted_label = 1)
false_positives_w2v = results_df_w2v[
    (results_df_w2v["true_label"] == 0) & (results_df_w2v["predicted_label"] == 1)
]

# Identify false negatives (true_label = 1, predicted_label = 0)
false_negatives_w2v = results_df_w2v[
    (results_df_w2v["true_label"] == 1) & (results_df_w2v["predicted_label"] == 0)
]

print("--- Word2Vec Model Failure Cases ---")
print(f"Total False Positives: {len(false_positives_w2v)}")
print(f"Total False Negatives: {len(false_negatives_w2v)}")

print("\n--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---")
if not false_positives_w2v.empty:
    display(
        false_positives_w2v[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false positives found.")

print("\n--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---")
if not false_negatives_w2v.empty:
    display(
        false_negatives_w2v[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false negatives found.")

--- Word2Vec Model Failure Cases ---
Total False Positives: 27241
Total False Negatives: 4479

--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
141575,Who are the NFL players with the most Super Bo...,How badly do most NFL players want to win a Su...,0,1
119595,Where can you find the summary of the deals th...,How do banks like Goldman Sachs JP Morgan Morg...,0,1
320836,Can I get a DSLR camera for rent in Chennai,Where can I rent a DSLR camera in ranchi,0,1
256455,How do I tell if I am a visual auditory or kin...,I learn by speaking to people or speaking to m...,0,1
4088,I got AIR 617 in a NEST 2015 The cutoff is 90 ...,I got AIR 617 in a NEST 2016 The cutoff is 90 ...,0,1

--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
218308,How should one prepare for a marathon,How can I learn marathon,1,0
19047,Do you think time travel is possible,Could time travel be a real thing Could it be ...,1,0
91303,Is reservation necessary in India,Do scstobc really need reservation in India,1,0
302533,What is a real success,What do you think about the real success,1,0
91523,What are the proper exercises to reduce your u...,How do I reduce body fat properly,1,0

In [ ]:
# Siamese LSTM on question1_clean & question2_clean
# Assumes: train_clean, test_clean already exist from train_test_split

import numpy as np
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Embedding, LSTM, GRU, Bidirectional
from tensorflow.keras.layers import Dense, Dropout, Lambda, Concatenate
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.metrics import AUC
import tensorflow as tf

# ---------------------------------------------------
# 1. Prepare texts and labels (WITHOUT changing DataFrames)
# ---------------------------------------------------

# Use only the cleaned text columns
train_q1 = train_clean["question1_clean"].astype(str).values
train_q2 = train_clean["question2_clean"].astype(str).values
test_q1  = test_clean["question1_clean"].astype(str).values
test_q2  = test_clean["question2_clean"].astype(str).values

# Labels
y_train = train_clean["is_duplicate"].astype(int).values
y_test  = test_clean["is_duplicate"].astype(int).values

# ---------------------------------------------------
# 2. Tokenizer on TRAIN text only (q1 + q2)
# ---------------------------------------------------
all_train_text = np.concatenate([train_q1, train_q2])

max_vocab_size = 50000   # you can adjust
tokenizer = Tokenizer(num_words=max_vocab_size, oov_token="<OOV>")
tokenizer.fit_on_texts(all_train_text)

# Convert to sequences
X_train_q1_seq = tokenizer.texts_to_sequences(train_q1)
X_train_q2_seq = tokenizer.texts_to_sequences(train_q2)
X_test_q1_seq  = tokenizer.texts_to_sequences(test_q1)
X_test_q2_seq  = tokenizer.texts_to_sequences(test_q2)

# Padding
max_len = 40  # you can tune this (e.g., 40/50/60)
X_train_q1 = pad_sequences(X_train_q1_seq, maxlen=max_len, padding="post", truncating="post")
X_train_q2 = pad_sequences(X_train_q2_seq, maxlen=max_len, padding="post", truncating="post")
X_test_q1  = pad_sequences(X_test_q1_seq,  maxlen=max_len, padding="post", truncating="post")
X_test_q2  = pad_sequences(X_test_q2_seq,  maxlen=max_len, padding="post", truncating="post")

vocab_size = min(max_vocab_size, len(tokenizer.word_index) + 1)

# ---------------------------------------------------
# 3. Build Siamese LSTM / GRU encoder
# ---------------------------------------------------

embed_dim = 128
lstm_units = 64

# Shared input shapes
input_q1 = Input(shape=(max_len,), name="input_q1")
input_q2 = Input(shape=(max_len,), name="input_q2")

# Shared embedding layer
embedding_layer = Embedding(
    input_dim=vocab_size,
    output_dim=embed_dim,
    input_length=max_len,
    mask_zero=True,
    name="shared_embedding"
)

# Shared encoder: you can switch LSTM <-> GRU easily
# encoder = Bidirectional(LSTM(lstm_units, return_sequences=False, dropout=0.2, recurrent_dropout=0.2),
#                         name="shared_bi_lstm")
encoder = Bidirectional(GRU(lstm_units, return_sequences=False, dropout=0.2, recurrent_dropout=0.2),
                        name="shared_bi_gru")

# Encode both questions with shared weights
x1 = embedding_layer(input_q1)
x2 = embedding_layer(input_q2)

enc_q1 = encoder(x1)
enc_q2 = encoder(x2)

# ---------------------------------------------------
# 4. Similarity / comparison layer
# ---------------------------------------------------
# L1 distance (absolute difference)
l1_dist = Lambda(lambda tensors: tf.math.abs(tensors[0] - tensors[1]),
                 name="l1_distance")([enc_q1, enc_q2])

# Element-wise square difference (L2-style)
l2_dist = Lambda(lambda tensors: tf.math.square(tensors[0] - tensors[1]),
                 name="l2_distance")([enc_q1, enc_q2])

# Concatenate original encodings + distances
merged = Concatenate(name="merge_features")([enc_q1, enc_q2, l1_dist, l2_dist])

# ---------------------------------------------------
# 5. Classifier head (sigmoid output)
# ---------------------------------------------------
dense = Dense(128, activation="relu")(merged)
dense = Dropout(0.3)(dense)
dense = Dense(64, activation="relu")(dense)
dense = Dropout(0.3)(dense)
output = Dense(1, activation="sigmoid", name="output")(dense)

model = Model(inputs=[input_q1, input_q2], outputs=output)
model.compile(
    loss="binary_crossentropy",
    optimizer=Adam(learning_rate=1e-3),
    metrics=["accuracy", AUC(name="auc")]
)

model.summary()

# ---------------------------------------------------
# 6. Train the Siamese model
# ---------------------------------------------------
history = model.fit(
    [X_train_q1, X_train_q2],
    y_train,
    batch_size=256,
    epochs=5,              # increase for better performance
    validation_split=0.1,  # from training data only
    verbose=1
)

# ---------------------------------------------------
# 7. Evaluate on TEST set
# ---------------------------------------------------
test_preds_proba = model.predict([X_test_q1, X_test_q2])
test_preds = (test_preds_proba >= 0.5).astype(int).ravel()

from sklearn.metrics import accuracy_score, classification_report

print("✅ Test Accuracy (Siamese RNN):", accuracy_score(y_test, test_preds))
print("\n📊 Classification Report (Test):\n")
print(classification_report(y_test, test_preds))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_q1            │ (None, 40)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_q2            │ (None, 40)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_embedding    │ (None, 40, 128)   │  6,400,000 │ input_q1[0][0],   │
│ (Embedding)         │                   │            │ input_q2[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_2         │ (None, 40)        │          0 │ input_q1[0][0]    │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ not_equal_3         │ (None, 40)        │          0 │ input_q2[0][0]    │
│ (NotEqual)          │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_bi_gru       │ (None, 128)       │     74,496 │ shared_embedding… │
│ (Bidirectional)     │                   │            │ not_equal_2[0][0… │
│                     │                   │            │ shared_embedding… │
│                     │                   │            │ not_equal_3[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ l1_distance         │ (None, 128)       │          0 │ shared_bi_gru[0]… │
│ (Lambda)            │                   │            │ shared_bi_gru[1]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ l2_distance         │ (None, 128)       │          0 │ shared_bi_gru[0]… │
│ (Lambda)            │                   │            │ shared_bi_gru[1]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ merge_features      │ (None, 512)       │          0 │ shared_bi_gru[0]… │
│ (Concatenate)       │                   │            │ shared_bi_gru[1]… │
│                     │                   │            │ l1_distance[0][0… │
│                     │                   │            │ l2_distance[0][0] │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 128)       │     65,664 │ merge_features[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_2 (Dropout) │ (None, 128)       │          0 │ dense_2[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 64)        │      8,256 │ dropout_2[0][0]   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dropout_3 (Dropout) │ (None, 64)        │          0 │ dense_3[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output (Dense)      │ (None, 1)         │         65 │ dropout_3[0][0]   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 6,548,481 (24.98 MB)

 Trainable params: 6,548,481 (24.98 MB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/5
1137/1137 ━━━━━━━━━━━━━━━━━━━━ 883s 761ms/step - accuracy: 0.7489 - auc: 0.8042 - loss: 0.5043 - val_accuracy: 0.8094 - val_auc: 0.8908 - val_loss: 0.4099
Epoch 2/5
1137/1137 ━━━━━━━━━━━━━━━━━━━━ 864s 760ms/step - accuracy: 0.8488 - auc: 0.9216 - loss: 0.3422 - val_accuracy: 0.8276 - val_auc: 0.9039 - val_loss: 0.3842
Epoch 3/5
1137/1137 ━━━━━━━━━━━━━━━━━━━━ 942s 777ms/step - accuracy: 0.8860 - auc: 0.9526 - loss: 0.2665 - val_accuracy: 0.8241 - val_auc: 0.9070 - val_loss: 0.3940
Epoch 4/5
1137/1137 ━━━━━━━━━━━━━━━━━━━━ 883s 777ms/step - accuracy: 0.9090 - auc: 0.9681 - loss: 0.2175 - val_accuracy: 0.8213 - val_auc: 0.9068 - val_loss: 0.4267
Epoch 5/5
1137/1137 ━━━━━━━━━━━━━━━━━━━━ 861s 758ms/step - accuracy: 0.9242 - auc: 0.9772 - loss: 0.1833 - val_accuracy: 0.8255 - val_auc: 0.9048 - val_loss: 0.4381
2526/2526 ━━━━━━━━━━━━━━━━━━━━ 97s 38ms/step
✅ Test Accuracy (Siamese RNN): 0.8232615125676027

📊 Classification Report (Test):

              precision    recall  f1-score   support

           0       0.90      0.81      0.85     50813
           1       0.72      0.85      0.78     29990

    accuracy                           0.82     80803
   macro avg       0.81      0.83      0.82     80803
weighted avg       0.84      0.82      0.83     80803

In [ ]:
!pip install -U sentence-transformers

Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.1.2)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.2)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.9.0+cu126)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: huggingface-hub>=0.20.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.0)
Requirement already satisfied: Pillow in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (11.3.0)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.20.0->sentence-transformers) (1.2.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.5 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.5)
Requirement already satisfied: nvidia-nvshmem-cu12==3.3.20 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.3.20)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.11.1.6)
Requirement already satisfied: triton==3.5.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.5.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.7.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->sentence-transformers) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2025.11.12)

In [ ]:
from sentence_transformers import SentenceTransformer, losses, InputExample
from sentence_transformers import models
from torch.utils.data import DataLoader
import torch

In [ ]:
# You can also try 'all-MiniLM-L6-v2' (faster, smaller, very good)
word_embedding_model = models.Transformer('bert-base-uncased')
pooling_model = models.Pooling(
    word_embedding_model.get_word_embedding_dimension(),
    pooling_mode_mean_tokens=True,        # mean pooling → sentence embedding
    pooling_mode_cls_token=False,
    pooling_mode_max_tokens=False,
)

model = SentenceTransformer(modules=[word_embedding_model, pooling_model])

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

In [ ]:
from sentence_transformers import SentenceTransformer
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

# ---------------------------------------------------
# 1. Read data from existing DataFrames (NO modification)
# ---------------------------------------------------
train_q1 = train_clean["question1_clean"].astype(str).tolist()
train_q2 = train_clean["question2_clean"].astype(str).tolist()
test_q1  = test_clean["question1_clean"].astype(str).tolist()
test_q2  = test_clean["question2_clean"].astype(str).tolist()

y_train = train_clean["is_duplicate"].astype(int).values
y_test  = test_clean["is_duplicate"].astype(int).values

# ---------------------------------------------------
# 2. Load Sentence-BERT (Bi-Encoder)
#    You can change the model name if needed
# ---------------------------------------------------
model = SentenceTransformer("paraphrase-MiniLM-L6-v2")

# ---------------------------------------------------
# 3. Encode Q1 and Q2 into dense sentence embeddings
# ---------------------------------------------------
emb_train_q1 = model.encode(train_q1, batch_size=64, show_progress_bar=True)
emb_train_q2 = model.encode(train_q2, batch_size=64, show_progress_bar=True)

emb_test_q1  = model.encode(test_q1,  batch_size=64, show_progress_bar=True)
emb_test_q2  = model.encode(test_q2,  batch_size=64, show_progress_bar=True)

# Each emb_* has shape: (n_samples, embedding_dim)

# ---------------------------------------------------
# 4. Build features for classifier from embeddings
#    Common trick: [|u - v| , u * v]  (element-wise)
# ---------------------------------------------------
def build_features(e1, e2):
    # e1, e2: (n_samples, d)
    abs_diff = np.abs(e1 - e2)
    prod     = e1 * e2
    return np.concatenate([abs_diff, prod], axis=1)

X_train = build_features(emb_train_q1, emb_train_q2)
X_test  = build_features(emb_test_q1,  emb_test_q2)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

# ---------------------------------------------------
# 5. Train a simple classifier (Logistic Regression)
# ---------------------------------------------------
clf = LogisticRegression(
    max_iter=1000,
    n_jobs=-1,
    verbose=1
)
clf.fit(X_train, y_train)

# ---------------------------------------------------
# 6. Evaluate on TEST set
# ---------------------------------------------------
y_pred = clf.predict(X_test)

modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/122 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/314 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Batches:   0%|          | 0/5051 [00:00<?, ?it/s]

Batches:   0%|          | 0/5051 [00:00<?, ?it/s]

Batches:   0%|          | 0/1263 [00:00<?, ?it/s]

Batches:   0%|          | 0/1263 [00:00<?, ?it/s]

X_train shape: (323212, 768)
X_test shape: (80803, 768)

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.

In [ ]:
from sklearn.metrics import accuracy_score, classification_report

# Predict on test set
y_pred = clf.predict(X_test)

print("✅ Test Accuracy (Sentence-BERT Bi-Encoder):", accuracy_score(y_test, y_pred))
print("\n📊 Classification Report (Test):\n")
print(classification_report(y_test, y_pred))

✅ Test Accuracy (Sentence-BERT Bi-Encoder): 0.807420516564979

📊 Classification Report (Test):

              precision    recall  f1-score   support

           0       0.84      0.86      0.85     50813
           1       0.75      0.73      0.74     29990

    accuracy                           0.81     80803
   macro avg       0.79      0.79      0.79     80803
weighted avg       0.81      0.81      0.81     80803

In [ ]:
import pandas as pd

# Create a DataFrame to hold the test data, true labels, and predictions
# Using test_preds from the Siamese RNN model
results_df_siamese = test_clean.copy()
results_df_siamese["true_label"] = y_test
results_df_siamese["predicted_label"] = test_preds

# Identify false positives (true_label = 0, predicted_label = 1)
false_positives_siamese = results_df_siamese[
    (results_df_siamese["true_label"] == 0) & (results_df_siamese["predicted_label"] == 1)
]

# Identify false negatives (true_label = 1, predicted_label = 0)
false_negatives_siamese = results_df_siamese[
    (results_df_siamese["true_label"] == 1) & (results_df_siamese["predicted_label"] == 0)
]

print("--- Siamese Bi-GRU Model Failure Cases ---")
print(f"Total False Positives: {len(false_positives_siamese)}")
print(f"Total False Negatives: {len(false_negatives_siamese)}")

print("\n--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---")
if not false_positives_siamese.empty:
    display(
        false_positives_siamese[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false positives found.")

print("\n--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---")
if not false_negatives_siamese.empty:
    display(
        false_negatives_siamese[
            ["question1_clean", "question2_clean", "true_label", "predicted_label"]
        ].head(5)
    )
else:
    print("No false negatives found.")

--- Siamese Bi-GRU Model Failure Cases ---
Total False Positives: 9884
Total False Negatives: 4397

--- Sample False Positives (Predicted Duplicate, Actual Not Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
4088,I got AIR 617 in a NEST 2015 The cutoff is 90 ...,I got AIR 617 in a NEST 2016 The cutoff is 90 ...,0,1
255222,Who are interested in startup in Pune,Is anyone interested in a startup in Pune,0,1
112977,Does Donald Trump think of himself as a charlatan,Is Donald Trump a charlatan,0,1
49214,What apps or services use the Square Connect API,What apps or services use the Square Commerce API,0,1
399547,Why is attempting suicide considered a crime,Why is committing suicide illegal,0,1

--- Sample False Negatives (Predicted Not Duplicate, Actual Duplicate) ---

,question1_clean,question2_clean,true_label,predicted_label
323205,What is the difference between a hobby and a h...,What is the difference between interest and ho...,1,0
208682,How do you cure a lisp on your own,How do you cure lisp,1,0
200965,Was todays UPSC prelims 2016 a tough paper Wha...,How was upsc prelims 2016,1,0
316630,If there any chance in the world to survive a ...,Its it feasible to survive a shot in the head ...,1,0
91523,What are the proper exercises to reduce your u...,How do I reduce body fat properly,1,0

In [ ]:
# ---------------------------------------------------
# 0. Install dependencies (run once)
# ---------------------------------------------------
# If not already installed:
# !pip install -U sentence-transformers

from sentence_transformers import CrossEncoder, InputExample
from torch.utils.data import DataLoader
import numpy as np
from sklearn.metrics import accuracy_score, classification_report, f1_score

# ---------------------------------------------------
# 1. Prepare data (READ-ONLY from train_clean / test_clean)
# ---------------------------------------------------

# Text columns
train_q1 = train_clean["question1_clean"].astype(str).tolist()
train_q2 = train_clean["question2_clean"].astype(str).tolist()
test_q1  = test_clean["question1_clean"].astype(str).tolist()
test_q2  = test_clean["question2_clean"].astype(str).tolist()

# Labels
y_train = train_clean["is_duplicate"].astype(float).values  # float for regression-style score
y_test  = test_clean["is_duplicate"].astype(int).values     # keep int for metrics

print("Train size:", len(train_q1))
print("Test size:", len(test_q1))

# ---------------------------------------------------
# 2. Build training examples for Cross-Encoder
# ---------------------------------------------------

train_examples = [
    InputExample(texts=[q1, q2], label=label)
    for q1, q2, label in zip(train_q1, train_q2, y_train)
]

# Optional: you can also create a small validation set from train_clean if you want

train_dataloader = DataLoader(train_examples, batch_size=16, shuffle=True)

# ---------------------------------------------------
# 3. Initialize Cross-Encoder
# ---------------------------------------------------
# This model is already pre-trained on Quora-style duplicates, but we still fine-tune on your data.
# You can change to another cross-encoder model if needed.

model_name = "cross-encoder/quora-roberta-base"
cross_encoder = CrossEncoder(model_name, num_labels=1)  # regression-style output in [0,1]

# ---------------------------------------------------
# 4. Train Cross-Encoder
# ---------------------------------------------------

num_epochs = 2  # start with 1; you can increase to 2-3 if Colab can handle it
warmup_steps = int(0.1 * len(train_dataloader))  # 10% of steps for warmup

cross_encoder.fit(
    train_dataloader=train_dataloader,
    epochs=num_epochs,
    warmup_steps=warmup_steps,
    output_path="output/cross_encoder_quora",  # saves model here (optional)
    use_amp=True  # mixed precision for speed on GPU
)

# If you want to reload later:
# cross_encoder = CrossEncoder("output/cross_encoder_quora", num_labels=1)

# ---------------------------------------------------
# 5. Predict scores on TRAIN + TEST (for threshold tuning)
# ---------------------------------------------------

# CrossEncoder expects list of [q1, q2] pairs
train_pairs = list(zip(train_q1, train_q2))
test_pairs  = list(zip(test_q1, test_q2))

# Predict similarity scores in [0, 1]
train_scores = cross_encoder.predict(train_pairs, batch_size=32)
test_scores  = cross_encoder.predict(test_pairs,  batch_size=32)

print("Example train scores:", train_scores[:5])
print("Example test scores:",  test_scores[:5])

# ---------------------------------------------------
# 6. Find best threshold on TRAIN (based on F1)
# ---------------------------------------------------

thresholds = np.linspace(0.0, 1.0, 101)
best_thr = 0.5
best_f1 = -1.0

for thr in thresholds:
    y_train_pred = (train_scores >= thr).astype(int)
    f1 = f1_score(y_train.astype(int), y_train_pred)
    if f1 > best_f1:
        best_f1 = f1
        best_thr = thr

print(f"🔍 Best threshold on TRAIN: {best_thr:.3f} with F1 = {best_f1:.4f}")

# ---------------------------------------------------
# 7. Evaluate on TEST set using best threshold
# ---------------------------------------------------

y_test_pred = (test_scores >= best_thr).astype(int)

test_acc = accuracy_score(y_test, y_test_pred)
print(f"\n✅ Test Accuracy (Cross-Encoder): {test_acc:.4f}\n")

print("📊 Classification Report (Test):\n")
print(classification_report(y_test, y_test_pred))

Train size: 323212
Test size: 80803

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/608 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json: 0.00B [00:00, ?B/s]

README.md: 0.00B [00:00, ?B/s]

/usr/local/lib/python3.12/dist-packages/notebook/notebookapp.py:191: SyntaxWarning: invalid escape sequence '\/'
  | |_| | '_ \/ _` / _` |  _/ -_)
wandb: Logging into wandb.ai. (Learn how to deploy a W&B server locally: https://wandb.me/wandb-server)
wandb: You can find your API key in your browser here: https://wandb.ai/authorize?ref=models
wandb: Paste an API key from your profile and hit enter:wandb: WARNING If you're specifying your api key in code, ensure this code is not shared publicly.
wandb: WARNING Consider setting the WANDB_API_KEY environment variable, or running `wandb login` from the command line.
wandb: No netrc file found, creating one.
wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc
wandb: Currently logged in as: sonallimajumdar25 (sonallimajumdar25-iit-bombay) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

/usr/local/lib/python3.12/dist-packages/torch/utils/data/dataloader.py:668: UserWarning: 'pin_memory' argument is set as true but no accelerator is found, then device pinned memory won't be used.
  warnings.warn(warn_msg)

In [ ]:
import numpy as np
import pandas as pd
from sentence_transformers import CrossEncoder
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    precision_recall_fscore_support
)

# ---------------------------------------------------
# 1. (OPTIONAL) Reload the fine-tuned CrossEncoder
#    Skip this if `cross_encoder` is already in memory.
# ---------------------------------------------------
# cross_encoder = CrossEncoder("output/cross_encoder_quora", num_labels=1)

# ---------------------------------------------------
# 2. Prepare unseen TEST data (READ-ONLY)
# ---------------------------------------------------
test_q1 = test_clean["question1_clean"].astype(str).tolist()
test_q2 = test_clean["question2_clean"].astype(str).tolist()
y_test  = test_clean["is_duplicate"].astype(int).values

test_pairs = list(zip(test_q1, test_q2))

# ---------------------------------------------------
# 3. Predict scores with CrossEncoder
# ---------------------------------------------------
test_scores = cross_encoder.predict(test_pairs, batch_size=32)

# Use the best threshold you found during training
best_threshold = 0.440   # <-- replace if your best_thr is different

y_pred = (test_scores >= best_threshold).astype(int)

# ---------------------------------------------------
# 4. Global metrics
# ---------------------------------------------------
accuracy = accuracy_score(y_test, y_pred)
print(f"✅ Test Accuracy (Cross-Encoder on unseen data): {accuracy:.4f}\n")

print("📊 Classification Report (Test):\n")
print(classification_report(y_test, y_pred))

# ---------------------------------------------------
# 5. Performance Matrix (Confusion Matrix)
# ---------------------------------------------------
cm = confusion_matrix(y_test, y_pred, labels=[0, 1])

cm_df = pd.DataFrame(
    cm,
    index=["Actual_0_NotDup", "Actual_1_Dup"],
    columns=["Pred_0_NotDup", "Pred_1_Dup"]
)

print("\n📌 Performance Matrix (Confusion Matrix):\n")
print(cm_df)

# ---------------------------------------------------
# 6. Per-class precision/recall/F1 in numeric form (optional)
# ---------------------------------------------------
prec, rec, f1, support = precision_recall_fscore_support(
    y_test, y_pred, labels=[0, 1]
)

metrics_df = pd.DataFrame({
    "Class": [0, 1],
    "Precision": prec,
    "Recall": rec,
    "F1-score": f1,
    "Support": support
})

print("\n📌 Per-class Metrics:\n")
print(metrics_df)

NameError: name 'test_clean' is not defined

In [ ]:
!pip install -q sentence-transformers gradio

from sentence_transformers import CrossEncoder
import gradio as gr
import numpy as np

In [ ]:
# SAVE YOUR FINE-TUNED MODEL LOCALLY
save_path = "/content/cross_encoder_qa_model"

cross_encoder.save(save_path)

print("Model saved successfully at:", save_path)

In [ ]:
MODEL_PATH = "/content/cross_encoder_qa_model"  # your saved path
THRESHOLD = 0.440  # use the threshold you found during training

model = CrossEncoder(MODEL_PATH)
print("✅ Model loaded successfully!")

In [ ]:
def compare_questions(q1: str, q2: str) -> str:
    q1 = (q1 or "").strip()
    q2 = (q2 or "").strip()

    if not q1 or not q2:
        return "Please enter both questions."

    # CrossEncoder expects a list of [q1, q2] pairs
    score = float(model.predict([[q1, q2]])[0])
    label = "Duplicate" if score >= THRESHOLD else "Not Duplicate"

    # Only return the label as you requested
    return label

In [ ]:
import gradio as gr
with gr.Blocks() as demo:
    gr.Markdown("## 🔍 Question Duplicate Checker")

    q1_box = gr.Textbox(label="Question 1", lines=3, placeholder="Enter first question here")
    q2_box = gr.Textbox(label="Question 2", lines=3, placeholder="Enter second question here")

    compare_btn = gr.Button("Compare")

    result_box = gr.Textbox(label="Result", interactive=False)

    compare_btn.click(
        fn=compare_questions,
        inputs=[q1_box, q2_box],
        outputs=result_box
    )

demo.launch()  # in Colab you can do demo.launch(share=True) to get a public link